//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmugMug4writer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2.2")]
        public string ApiVersion {
            get {
                return ((string)(this["ApiVersion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("shOxMUSSF0xLchz65OMOrhuQvcTvh1QW")]
        public string ApiKey {
            get {
                return ((string)(this["ApiKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<style type=""text/css"">

.smugcontainer div {overflow: hidden;line-height: 1.1;margin-top: 10px;font-family: Verdana, arial, lucida, sans-serif;font-size: 85%;}

.smugimg li {
	float: left;
	display: block;
	width: 160px;
	height: 200px;
	margin-right: 10px;
	margin-bottom: 10px;
}

.smugimg li img {width: auto; height: auto; border: solid 1px #aaa; background: #555; padding: 2px; vertical-align: middle;}

.smugimg a {
	display: block;
	text-decoration: none;
}

.smugimg div {background-color:#ffffff;border:1px solid #2A2A2A;float:left;margin-bottom:10px;margin-right:10px;padding:3px 3px 8px;}

</style>
")]
        public string GalleryCSS {
            get {
                return ((string)(this["GalleryCSS"]));
            }
        }
    }
}
